version: '3.9' # optional since v1.27.0
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dbstore
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
    ports:
      - '5432:5432'
    volumes:
      - ./data_postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    environment:
      - PMA_HOST=mysql
    ports:
      - 8080:80
    depends_on:
      - mysql
